In [112]:
import pandas as pd
import numpy as np

In [113]:
data = pd.read_csv(r'C:\Users\d\Documents\Python\Hamoye_One_School\Classification_in_ML\data_for_uci_named.csv')

In [114]:
data.shape

(10000, 14)

In [115]:
data.head(12)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0   2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1   9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2   8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3   0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4   3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
5   6.999209  9.109247  3.784066  4.267788  4.429669 -1.857139 -0.670397   
6   6.710166  3.765204  6.929314  8.818562  2.397419 -0.614590 -1.208826   
7   6.953512  1.379125  5.719400  7.870307  3.224495 -0.748998 -1.186517   
8   4.689852  4.007747  1.478573  3.733787  4.041300 -1.410344 -1.238204   
9   9.841496  1.413822  9.769856  7.641616  4.727595 -1.991363 -0.857637   
10  5.930110  6.730873  6.245138  0.533288  2.327092 -0.702501 -1.116920   
11  5.381299  8.014521  8.095174  6.769248  5.507551 -1.972714 -1.849333   

          p4        g1        g2        g3        g4      stab     stabf  
0  -1.723086  0.650456  0.859578  0.887445  0.958034  0.055347  unstable  
1  -1.255012  0.413441  0.862414  0.562139  0.781760 -0.005957    stable  
2  -0.920492  0.163041  0.766689  0.839444  0.109853  0.003471  unstable  
3  -0.997374  0.446209  0.976744  0.929381  0.362718  0.028871  unstable  
4  -0.554305  0.797110  0.455450  0.656947  0.820923  0.049860  unstable  
5  -1.902133  0.261793  0.077930  0.542884  0.469931 -0.017385    stable  
6  -0.574004  0.177890  0.397977  0.402046  0.376630  0.005954  unstable  
7  -1.288980  0.371385  0.633204  0.732741  0.380544  0.016634  unstable  
8  -1.392751  0.269708  0.250364  0.164941  0.482439 -0.038677    stable  
9  -1.878594  0.376356  0.544415  0.792039  0.116263  0.012383  unstable  
10 -0.507671  0.239816  0.563110  0.164461  0.753701 -0.028411    stable  
11 -1.685505  0.359974  0.173569  0.349144  0.628860  0.028130  unstable

In [116]:
data.isna().sum()

tau1     0
tau2     0
tau3     0
tau4     0
p1       0
p2       0
p3       0
p4       0
g1       0
g2       0
g3       0
g4       0
stab     0
stabf    0
dtype: int64

In [117]:
df = data.drop(columns = 'stab')

In [118]:
df.head(12)

tau1      tau2      tau3      tau4        p1        p2        p3  \
0   2.959060  3.079885  8.381025  9.780754  3.763085 -0.782604 -1.257395   
1   9.304097  4.902524  3.047541  1.369357  5.067812 -1.940058 -1.872742   
2   8.971707  8.848428  3.046479  1.214518  3.405158 -1.207456 -1.277210   
3   0.716415  7.669600  4.486641  2.340563  3.963791 -1.027473 -1.938944   
4   3.134112  7.608772  4.943759  9.857573  3.525811 -1.125531 -1.845975   
5   6.999209  9.109247  3.784066  4.267788  4.429669 -1.857139 -0.670397   
6   6.710166  3.765204  6.929314  8.818562  2.397419 -0.614590 -1.208826   
7   6.953512  1.379125  5.719400  7.870307  3.224495 -0.748998 -1.186517   
8   4.689852  4.007747  1.478573  3.733787  4.041300 -1.410344 -1.238204   
9   9.841496  1.413822  9.769856  7.641616  4.727595 -1.991363 -0.857637   
10  5.930110  6.730873  6.245138  0.533288  2.327092 -0.702501 -1.116920   
11  5.381299  8.014521  8.095174  6.769248  5.507551 -1.972714 -1.849333   

          p4        g1        g2        g3        g4     stabf  
0  -1.723086  0.650456  0.859578  0.887445  0.958034  unstable  
1  -1.255012  0.413441  0.862414  0.562139  0.781760    stable  
2  -0.920492  0.163041  0.766689  0.839444  0.109853  unstable  
3  -0.997374  0.446209  0.976744  0.929381  0.362718  unstable  
4  -0.554305  0.797110  0.455450  0.656947  0.820923  unstable  
5  -1.902133  0.261793  0.077930  0.542884  0.469931    stable  
6  -0.574004  0.177890  0.397977  0.402046  0.376630  unstable  
7  -1.288980  0.371385  0.633204  0.732741  0.380544  unstable  
8  -1.392751  0.269708  0.250364  0.164941  0.482439    stable  
9  -1.878594  0.376356  0.544415  0.792039  0.116263  unstable  
10 -0.507671  0.239816  0.563110  0.164461  0.753701    stable  
11 -1.685505  0.359974  0.173569  0.349144  0.628860  unstable

In [119]:
df['stabf'].value_counts()

unstable    6380
stable      3620
Name: stabf, dtype: int64

In [120]:
x = df.drop(columns = 'stabf')
y = df['stabf']

In [121]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1)

In [122]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()

standardised_train_df = scaler.fit_transform(x_train)
standardised_train_df = pd.DataFrame(standardised_train_df)
standardised_train_df

0         1         2         3         4         5         6  \
0     0.367327 -0.986042  0.650447  1.547527 -0.291490  0.061535  1.293862   
1    -0.064659  0.089437  1.035079 -1.641494  0.619865 -0.067235 -1.502925   
2    -1.467850  1.298418 -0.502536  1.166046 -0.180521  0.490603  0.682560   
3     0.820081  0.529920  1.299657 -1.141975 -0.812854 -0.763632  1.521579   
4     0.665424 -1.425627  0.312300  0.919137 -1.614296  0.760315  1.422019   
...        ...       ...       ...       ...       ...       ...       ...   
7995  1.551314  0.007408 -1.177640  1.016898 -0.397177  0.759820 -0.636951   
7996  1.015925 -0.223483 -1.489381 -1.479078  0.451468 -0.731994  0.990355   
7997  0.657609 -0.722756 -1.405888 -0.274301 -0.012584  1.438694 -0.364266   
7998 -0.059316 -1.260532 -1.010471 -0.877808 -0.779769  0.828824  0.516923   
7999 -1.473214  0.638438  0.250122 -0.996484  1.950944 -1.163800 -0.732842   

             7         8         9        10        11  
0    -0.845074  0.160918  0.339859  0.585568  0.492239  
1     0.486613 -0.293143 -1.558488  1.429649 -1.443521  
2    -0.855302  1.399350  1.451534 -1.045743  0.492489  
3     0.658780 -0.958319  1.361958  1.604140  0.275303  
4     0.639243  1.676895  0.695660  1.137504 -1.312575  
...        ...       ...       ...       ...       ...  
7995  0.572703 -1.209413  0.313976 -1.625728 -0.637401  
7996 -1.048148 -1.094647 -0.755209  0.734821 -0.304433  
7997 -1.046683  1.253539  0.293100 -1.550587  0.810344  
7998  0.018984 -0.182448 -0.388255 -0.726781  1.667916  
7999 -1.513302  1.230438 -1.174110  1.179282  0.783627  

[8000 rows x 12 columns]

In [123]:
standardised_test_df = scaler.fit_transform(x_test)
standardised_test_df = pd.DataFrame(standardised_test_df)
standardised_test_df

0         1         2         3         4         5         6  \
0     0.592163 -0.420565  1.472472  1.093036  0.426786 -1.504594 -0.792677   
1     0.199183  0.364543 -0.190076 -0.518473 -0.229402 -1.071766  0.427103   
2    -1.086035 -0.321834 -0.873505  0.011761 -0.977094  0.094896  0.813041   
3    -0.087014 -1.113357  0.361518 -1.684316  0.792280 -1.649041  0.410662   
4     0.873004  1.425833  0.080476  1.681022 -0.154247 -0.024315 -0.197525   
...        ...       ...       ...       ...       ...       ...       ...   
1995  1.119526 -0.682371 -1.362900  1.261070  0.266377 -0.817583  0.745388   
1996 -1.084900 -0.815496  1.010385  0.326900 -0.167494  0.322284  1.002069   
1997  0.947138 -1.668313 -1.629077  0.518632 -1.576793  1.566742  0.094662   
1998 -1.127354  0.184573 -0.238207  0.409415 -1.205991  0.718553  0.029632   
1999 -1.385560  1.499043  0.272971  1.480274  0.682028 -1.498433 -0.789188   

             7         8         9        10        11  
0     1.600201 -0.925703  1.175287 -1.492644  1.086291  
1     1.052337 -1.655910 -0.395949  1.412703  1.227535  
2     0.751381  1.450284 -1.444370  0.654216 -1.679799  
3    -0.084473  0.066085 -1.679450 -0.349573  1.057439  
4     0.485988  0.119716 -1.475773  0.957057 -0.817608  
...        ...       ...       ...       ...       ...  
1995 -0.370774  0.471600 -0.114316 -1.251379 -1.280864  
1996 -1.049289  0.941736  0.899379 -1.050349 -1.091915  
1997  0.997188 -1.261183  0.128899  0.576286  1.320848  
1998  1.293823  1.518021  0.800172 -1.348463 -0.799858  
1999  1.155547  0.479208 -0.920581  0.009039  1.190559  

[2000 rows x 12 columns]

## Random Tree Classifier

In [124]:
from sklearn.ensemble import RandomForestClassifier
clf = RandomForestClassifier(random_state = 1)

clf.fit(standardised_train_df, y_train)

RandomForestClassifier(random_state=1)

In [125]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions_0 = clf.predict(standardised_test_df)

In [126]:
cnf_mat0 = confusion_matrix(y_true = y_test, y_pred = new_predictions_0, labels = ['unstable', 'stable'])
cnf_mat0

array([[1232,   56],
       [  88,  624]], dtype=int64)

In [127]:
accuracy0 = accuracy_score(y_true = y_test, y_pred = new_predictions_0)
print( 'Accuracy: {}'.format(round(accuracy0*100), 2))
accuracy0

Accuracy: 93.0


0.928

In [128]:
precision0 = precision_score(y_true = y_test, y_pred = new_predictions_0, pos_label = 'stable')
print('Precision: {}'.format(round(precision0*100 ), 2))

Precision: 92.0


In [129]:
recall0 = recall_score(y_true = y_test, y_pred = new_predictions_0, pos_label = 'stable')
print('Recall: {}'.format(round(recall0*100 ), 2)) 

Recall: 88.0


In [130]:
f1_score0 = f1_score(y_true = y_test, y_pred = new_predictions_0, pos_label= 'stable')
print('F1: {}'.format(round(f1_score0*100), 2))

F1: 90.0


In [131]:
from sklearn.metrics import classification_report
print(classification_report(y_true = y_test, y_pred = new_predictions_0, labels = ['unstable', 'stable']))

              precision    recall  f1-score   support

    unstable       0.93      0.96      0.94      1288
      stable       0.92      0.88      0.90       712

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



## Extra Trees Classifier

In [171]:
from sklearn.ensemble import ExtraTreesClassifier
tree = ExtraTreesClassifier(random_state = 1)

tree.fit(standardised_train_df, y_train).feature_importances_

array([0.11739736, 0.11844468, 0.11316851, 0.11546569, 0.03950675,
       0.04037132, 0.04070628, 0.04057864, 0.08978291, 0.09367636,
       0.09688268, 0.09401882])

In [133]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions_1 = tree.predict(standardised_test_df)

In [134]:
cnf_mat1 = confusion_matrix(y_true = y_test, y_pred = new_predictions_1, labels = ['unstable', 'stable'])
cnf_mat1

array([[1250,   38],
       [ 110,  602]], dtype=int64)

In [167]:
accuracy1 = accuracy_score(y_true = y_test, y_pred = new_predictions_1)
print( 'Accuracy: {}'.format(round(accuracy1*100), 2))

Accuracy: 93.0


In [136]:
precision1 = precision_score(y_true = y_test, y_pred = new_predictions_1, pos_label = 'stable')
print('Precision: {}'.format(round(precision1*100), 2))

Precision: 94.0


In [137]:
recall1 = recall_score(y_true = y_test, y_pred = new_predictions_1, pos_label = 'stable')
print('Recall: {}'.format(round(recall1*100), 2))

Recall: 85.0


In [138]:
f1_score1 = f1_score(y_true = y_test, y_pred = new_predictions_1, pos_label= 'stable')
print('F1: {}'.format(round(f1_score1*100), 2))

F1: 89.0


In [139]:
from sklearn.metrics import classification_report
print(classification_report(y_true = y_test, y_pred = new_predictions_1, labels = ['unstable', 'stable']))

              precision    recall  f1-score   support

    unstable       0.92      0.97      0.94      1288
      stable       0.94      0.85      0.89       712

    accuracy                           0.93      2000
   macro avg       0.93      0.91      0.92      2000
weighted avg       0.93      0.93      0.93      2000



## Extra Trees Classifier & RandomizedSearchCV

In [140]:
n_estimators = [50, 100, 300, 500, 1000]
min_samples_split = [2, 3, 5, 7, 9]
min_samples_leaf = [1, 2, 4, 6, 8]
max_features = ['auto', 'sqrt', 'log2', None]

hyperparameter_grid = {'n_estimators' : n_estimators,
                       'min_samples_leaf' : min_samples_leaf,
                       'min_samples_split' : min_samples_split,
                       'max_features' : max_features}

In [141]:
from sklearn.ensemble import ExtraTreesClassifier
tree = ExtraTreesClassifier(max_features=None, min_samples_leaf=8, min_samples_split=2, n_estimators=1000, random_state = 1)

In [142]:
from sklearn.model_selection import RandomizedSearchCV
random = RandomizedSearchCV(estimator = tree, param_distributions = hyperparameter_grid, cv=5, n_iter=10, scoring = 'accuracy', n_jobs = -1, verbose = 1, random_state = 1)

random.fit(standardised_train_df, y_train)


Fitting 5 folds for each of 10 candidates, totalling 50 fits


[Parallel(n_jobs=-1)]: Using backend LokyBackend with 2 concurrent workers.
[Parallel(n_jobs=-1)]: Done  46 tasks      | elapsed:  2.7min
[Parallel(n_jobs=-1)]: Done  50 out of  50 | elapsed:  2.9min finished


RandomizedSearchCV(cv=5,
                   estimator=ExtraTreesClassifier(max_features=None,
                                                  min_samples_leaf=8,
                                                  n_estimators=1000,
                                                  random_state=1),
                   n_jobs=-1,
                   param_distributions={'max_features': ['auto', 'sqrt', 'log2',
                                                         None],
                                        'min_samples_leaf': [1, 2, 4, 6, 8],
                                        'min_samples_split': [2, 3, 5, 7, 9],
                                        'n_estimators': [50, 100, 300, 500,
                                                         1000]},
                   random_state=1, scoring='accuracy', verbose=1)

In [143]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions_2 = random.predict(standardised_test_df)

In [144]:
cnf_mat2 = confusion_matrix(y_true = y_test, y_pred = new_predictions_2, labels = ['unstable', 'stable'])
cnf_mat2

array([[1238,   50],
       [  93,  619]], dtype=int64)

In [169]:
accuracy2 = accuracy_score(y_true = y_test, y_pred = new_predictions_2)
print( 'Accuracy: {}'.format(round(accuracy2*100), 2))

Accuracy: 93.0


In [146]:
precision2 = precision_score(y_true = y_test, y_pred = new_predictions_2, pos_label = 'stable')
print('Precision: {}'.format(round(precision2*100), 2))

Precision: 93.0


In [147]:
recall2 = recall_score(y_true = y_test, y_pred = new_predictions_2, pos_label = 'stable')
print('Recall: {}'.format(round(recall2*100), 2)) 

Recall: 87.0


In [148]:
f1_score2 = f1_score(y_true = y_test, y_pred = new_predictions_2, pos_label= 'stable')
print('F1: {}'.format(round(f1_score2*100), 2))

F1: 90.0


In [149]:
from sklearn.metrics import classification_report
print(classification_report(y_true = y_test, y_pred = new_predictions_2, labels = ['unstable', 'stable']))

              precision    recall  f1-score   support

    unstable       0.93      0.96      0.95      1288
      stable       0.93      0.87      0.90       712

    accuracy                           0.93      2000
   macro avg       0.93      0.92      0.92      2000
weighted avg       0.93      0.93      0.93      2000



## XGBoost

In [150]:
from xgboost import XGBClassifier

xg_model = XGBClassifier(random_state = 1)
xg_model.fit(standardised_train_df, y_train)

XGBClassifier(random_state=1)

In [151]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions_3 = xg_model.predict(standardised_test_df)

In [152]:
cnf_mat3 = confusion_matrix(y_true = y_test, y_pred = new_predictions_3, labels = ['unstable', 'stable'])
cnf_mat3

array([[1239,   49],
       [ 113,  599]], dtype=int64)

In [153]:
accuracy3 = accuracy_score(y_true = y_test, y_pred = new_predictions_3)
print( 'Accuracy: {}'.format(round(accuracy3*100), 2))

Accuracy: 92.0


In [154]:
precision3 = precision_score(y_true = y_test, y_pred = new_predictions_3, pos_label = 'stable')
print('Precision: {}'.format(round(precision3*100), 2))

Precision: 92.0


In [155]:
recall3 = recall_score(y_true = y_test, y_pred = new_predictions_3, pos_label = 'stable')
print('Recall: {}'.format(round(recall3*100), 2))

Recall: 84.0


In [156]:
f1_score3 = f1_score(y_true = y_test, y_pred = new_predictions_3, pos_label= 'stable')
print('F1: {}'.format(round(f1_score3*100), 2))

F1: 88.0


In [157]:
from sklearn.metrics import classification_report
print(classification_report(y_true = y_test, y_pred = new_predictions_3, labels = ['unstable', 'stable']))

              precision    recall  f1-score   support

    unstable       0.92      0.96      0.94      1288
      stable       0.92      0.84      0.88       712

    accuracy                           0.92      2000
   macro avg       0.92      0.90      0.91      2000
weighted avg       0.92      0.92      0.92      2000



## LightGBM

In [158]:
from lightgbm import LGBMClassifier

lgbm_model = LGBMClassifier(random_state = 1)
lgbm_model.fit(standardised_train_df, y_train)

LGBMClassifier(random_state=1)

In [159]:
from sklearn.metrics import recall_score, accuracy_score, precision_score, f1_score, confusion_matrix
new_predictions_4 = lgbm_model.predict(standardised_test_df)

In [160]:
cnf_mat4 = confusion_matrix(y_true = y_test, y_pred = new_predictions_4, labels = ['unstable', 'stable'])
cnf_mat4

array([[1236,   52],
       [  77,  635]], dtype=int64)

In [161]:
accuracy4 = accuracy_score(y_true = y_test, y_pred = new_predictions_4)
print( 'Accuracy: {}'.format(round(accuracy4*100), 2))

Accuracy: 94.0


In [162]:
precision4 = precision_score(y_true = y_test, y_pred = new_predictions_4, pos_label = 'stable')
print('Precision: {}'.format(round(precision4*100), 2))

Precision: 92.0


In [163]:
recall4 = recall_score(y_true = y_test, y_pred = new_predictions_4, pos_label = 'stable')
print('Recall: {}'.format(round(recall4*100), 2))

Recall: 89.0


In [164]:
f1_score4 = f1_score(y_true = y_test, y_pred = new_predictions_4, pos_label= 'stable')
print('F1: {}'.format(round(f1_score4*100), 2))

F1: 91.0


In [165]:
from sklearn.metrics import classification_report
print(classification_report(y_true = y_test, y_pred = new_predictions_4, labels = ['unstable', 'stable']))

              precision    recall  f1-score   support

    unstable       0.94      0.96      0.95      1288
      stable       0.92      0.89      0.91       712

    accuracy                           0.94      2000
   macro avg       0.93      0.93      0.93      2000
weighted avg       0.94      0.94      0.94      2000

